from __future__ import annotations
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, List, Sequence, Tuple

Color = Tuple[int, int, int]

@dataclass
class Palette:
    name: str
    colors: List[Color]

    def __post_init__(self) -> None:
        self.colors = [validate_color(c) for c in self.colors]

    def padded256(self, fill: Color = (0, 0, 0)) -> "Palette":
        colors = list(self.colors[:256])
        while len(colors) < 256:
            colors.append(fill)
        return Palette(self.name, colors)

    def unique_report(self) -> dict[Color, list[int]]:
        seen: dict[Color, list[int]] = {}
        for i, c in enumerate(self.colors):
            seen.setdefault(c, []).append(i)
        return {c: idxs for c, idxs in seen.items() if len(idxs) > 1}

    def to_gpl(self, path: str | Path, columns: int = 16) -> None:
        write_gpl(path, self.name, self.colors, columns=columns)


def validate_color(c: Sequence[int]) -> Color:
    if len(c) != 3:
        raise ValueError(f"RGB color must have three components: {c!r}")
    r, g, b = (int(x) for x in c)
    for x in (r, g, b):
        if x < 0 or x > 255:
            raise ValueError(f"RGB component out of range: {c!r}")
    return (r, g, b)


def read_gpl(path: str | Path) -> Palette:
    path = Path(path)
    colors: list[Color] = []
    name = path.stem
    with path.open("r", encoding="utf-8", errors="replace") as f:
        first = f.readline().strip()
        if first != "GIMP Palette":
            raise ValueError(f"Not a GIMP .gpl palette: {path}")
        for line in f:
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            if stripped.startswith("Name:"):
                name = stripped.split(":", 1)[1].strip() or name
                continue
            if stripped.startswith("Columns:"):
                continue
            parts = stripped.split()
            if len(parts) >= 3 and all(p.lstrip("+-").isdigit() for p in parts[:3]):
                colors.append(validate_color(tuple(int(p) for p in parts[:3])))
    return Palette(name, colors)


def write_gpl(path: str | Path, name: str, colors: Iterable[Color], columns: int = 16,
              names: Sequence[str] | None = None) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        f.write("GIMP Palette\n")
        f.write(f"Name: {name}\n")
        f.write(f"Columns: {columns}\n")
        f.write("# Generated by liero-gimp-toolkit\n")
        for i, (r, g, b) in enumerate(colors):
            entry = names[i] if names and i < len(names) else f"index_{i:03d}"
            f.write(f"{r:3d} {g:3d} {b:3d}\t{entry}\n")


def load_indexed_png_palette(path: str | Path) -> Palette:
    """Load the palette of an indexed PNG using Pillow, if available."""
    try:
        from PIL import Image
    except Exception as exc:  # pragma: no cover
        raise RuntimeError("Pillow is required for PNG palette import: pip install pillow") from exc
    path = Path(path)
    img = Image.open(path)
    if img.mode != "P":
        raise ValueError(f"PNG is not indexed/palette mode: {path}")
    raw = img.getpalette() or []
    colors = [tuple(raw[i:i+3]) for i in range(0, min(len(raw), 768), 3)]
    return Palette(path.stem, colors).padded256()


def nearest_color_index(color: Color, palette: Sequence[Color], candidates: Sequence[int] | None = None) -> int:
    if candidates is None:
        candidates = range(len(palette))
    cr, cg, cb = color
    best_i = None
    best_d = 10**18
    for i in candidates:
        pr, pg, pb = palette[i]
        d = (cr - pr) ** 2 + (cg - pg) ** 2 + (cb - pb) ** 2
        if d < best_d:
            best_d = d
            best_i = i
    if best_i is None:
        raise ValueError("No candidate palette indices")
    return best_i
